### ISSUE TITLE
Improve default generated FIL key UX

### ISSUE THREAD

**Issue by gallexis** [myelnet/pop#123]

**Comment by tchardin** [comment]
@gallexis can you also double check the default address is properly persisted between node restarts?

I think we might need to add 2 cli commands:
```bash
$ pop export-key <address> <file-location>
# and
$ pop transfer <from-address> <to-address> <amount>
```

**Comment by gallexis** [comment]
Ok I will create the 2 CLI commands 👍
Also, I think when a user generates a new a default address, I think it would be better to generate it straight in the "setupWallet" function rather than delaying it for later in the init of the exchange

**Comment by tchardin** [comment]
Mmm the wallet instance is created when initializing the exchange so it doesn't exist yet when calling setupWallet. Maybe you can figure something out

**Comment by gallexis** [comment]
Yeah indeed it's not as easy as I thought it would be but I'll try something
