### ISSUE TITLE
Add `-maxppb` flag to the start config

### ISSUE THREAD

**Issue by tchardin** [myelnet/pop#131]
`-maxppb` (max price per byte) is a parameter currently used for the `get` command. We should also give the option to change this parameter globally when starting the node. To do this, add a survey step in the start command so it is also saved on the JSON config file. The default should be `5` and display the unit (attoFIL).

**Comment by gallexis** [comment]
does it mean that by default we take the maxppb sent in the get, but when not set (or = 0) we take the one set in the Start?
