### ISSUE TITLE
Check default address balance before executing retrievals

### ISSUE THREAD

**Issue by tchardin** [myelnet/pop#142]
Both client and providers need a minimum amount of FIL to execute a paid retrieval. On the client side, we should be checking if there are sufficient funds in the wallet before executing an offer. This should be implemented in `node.Load` during triage when selecting an offer to execute.
On the provider side we should be checking if there are sufficient funds in the wallet as well in order to pay for gas fees when collecting funds. This should be executed at the `exchange.handleQuery` level. I think 0.1FIL should be enough for most gas transactions.
Balance can be read using the filecoin API, `StateGetActor` and reading the Balance property on Actor type.

**Comment by tchardin** [comment]
This is blocked by #136

**Comment by gallexis** [comment]
can I use Balance() instead? https://github.com/myelnet/pop/blob/main/wallet/wallet.go#L486
