### ISSUE TITLE
Add websocket transport

### ISSUE THREAD

**Issue by tchardin** [myelnet/pop#143]
I believe websocket transport is already enabled by default, all we need is to add `"/ip4/0.0.0.0/tcp/41505/ws"` to the listening addresses.

**Comment by gallexis** [comment]
Might be for another issue, but I'm thinking about using a connection multiplexing library for handling all our protocols (http, tcp, rpc, websocket) on 1 port.
It would make the codebase more cleaner : https://github.com/soheilhy/cmux

**Comment by tchardin** [comment]
> It would make the codebase more cleaner : https://github.com/soheilhy/cmux

Yeah that's not really related to this issue.

**Comment by tchardin** [comment]
Closed by #148
