### ISSUE TITLE
Use a Myel node for bootstrap and gate connections from IPFS nodes

### ISSUE THREAD

**Issue by tchardin** [myelnet/pop#163]
- Confirm that a Myel node can be used as a bootstrap node (I think the DHT server mode is enabled by default but I might be wrong so you can double check by connecting 2 nodes to a 3rd Myel node and see if they discover each other.
- Use a [connection gater](https://pkg.go.dev/github.com/libp2p/go-libp2p/p2p/net/conngater#BasicConnectionGater) to prevent Myel nodes from connecting to IPFS nodes. Two ways to go about it would be either checking the user agent header or the protocols a peer supports.

**Comment by tchardin** [comment]
cc @alexander-camuto

**Comment by alexander-camuto** [comment]
Context for needing is as follows. 

If a peer with non-Myel peers in their routing table (i.e regular IPFS peers) connects to our regular IPFS bootstrap node, these peers in their routing table can connect to other Myel nodes, flooding the network with non-Myel related connections. 

This allows for a simple attack vector: 

- Node A connects to a custom bootstrrap which is connected to the entire network of IPFS peers
- Node A routing table is now full of non-Myel peers
- Node A then connects to our bootstrap explicitly 
- Our network is now flooded with non-Myel peers

The solutions @tchardin describes above help to contrain connections within the network to Myel peers.

**Comment by gallexis** [comment]
I confirm that when connecting 2 different nodes ( A & B) to the same bootstrap node (C), A & B eventually discover each other.

**Comment by gallexis** [comment]
I made a first draft where, upon reception of a EvtPeerIdentificationCompleted we check if the peer supports the HeyProtocol (since it's the first message to be sent the message should be a HeyMessage), if not, we block him and close the stream connection.

Also, think the best way to handle this case would be to act at the DHT level, where peers would only advertise on protocols they support. 
There is an issue [there](https://github.com/libp2p/go-libp2p-kad-dht/issues/302) but it's still pending and I've subscribed to see the advancement.

**Comment by gallexis** [comment]
see https://github.com/myelnet/pop/pull/168

**Comment by gallexis** [comment]
Here is the result when I add an ipfs bootstrap address to a Myel node,

- Before adding the DHT prefix : 

```shell
PeerID         12D3KooWAMqDCQXuqujBFZieQDWR895byy8JH9F7WfZqt3AWBXSv
Addresses      [/ip6/2001:bc8:1830:322::1/tcp/41503 /ip6/::1/tcp/41503 /ip4/10.19.70.69/tcp/41504 /ip4/127.0.0.1/tcp/41504 /ip4/10.19.70.69/tcp/41505/ws /ip4/127.0.0.1/tcp/41505/ws /ip4/51.158.181.154/tcp/41504]
Peers          [12D3KooWGixMT2T3AWDNF7985fani6scQSZKSsQ1yVFTdJX7pyDs QmZzNntkgVf8gWsosSsAKWz2iMQjHrcRTvJSciZgBKDVW2 Qmf2GSe6b1zwe2teWLhQ2Yq1yZxNyGwMjefF5a9XGcSvyj QmfSbQVo1DTEMSqzEVknZkrN15q4gdiHmzWuR1LcV7yuii QmNbouTEkLiaARmQxk3aQZhQ2XoszySoeHhugAVKbtf9FX 12D3KooWML7NMZudk8H4v1AptitsTZdDqLKgEzoAdLUwuKPqkLyy QmWhCbiWGDzCpPqbske3Li9PdP1u2UX7tCrVPreWuAAr9S 12D3KooWBUbqbNQP22Hi8iyaUxGUQ5q2g4pcRaFSzx6EvcmDj9Ab 12D3KooWNCZH3seb1FqjJegavy7UgKu8JWaXPjhLZgR7tTw4BXAV 12D3KooWNVqoQHwqZi2f8G3W3tMniYakeAxThYusKFT7TCNMvK2p QmVVm2Uzryxk6p4oLjkejnbbUZKiELZygsxwzo17mFQsLG 12D3KooWBcjTbHzyv4buGBLE52UJuE63MeyVQKAp8QPrZMwnpq9m QmPk8uBH9VwjEF6f14p8vP2GWqCYN66SoPQ84RecMy8bDn 12D3KooWQ2JYyCuXLjv7rwWokRg7qfkgFy7nufD7iQY6WJsmmgPG QmbEmhHUexH12aYFq6rEe7PwDLLq8gCX3mmcHqve1W6F8K QmSzTP8dhMAXsUsa9JgnPRNdKXsNnFt34HUToaVM8wDPpX QmaLVaprFwahHf3gDf8DLbkYGKenjTCL8vkBxLDtu8Mmme QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN 12D3KooWMETXkWySAajFMqjiq8Q9xwMR8ceBrEAQFh6k8KHLAPNy 12D3KooWE48wcXK7brQY1Hw7LhjF3xdiFegLnCAibqDtyrgdxNgn Qmbz9KKLeBTZBDsRubW2hWh5xSSSSnHWXNvJqUHhm81aXf QmSPz3WfZ1xCq6PCFQj3xFHAPBRUudbogcDPSMtwkQzxGC 12D3KooWJ21kVGMBp8PpRQMpgf44hVsVG2mPR9TzprGR3XQKN1J8 QmRP4ogL8h69D7a8GerTRknax7nk9evGpeM5RgmW24Wn61 QmT4wsvhbBLMA7pggyXFfjbFrMfXkPo8meB7BdSkgbAA35 12D3KooWKAhmdjz9ErarC7bg9ZmLj8sbZYCqhWaVTxndmRrK1nuW 12D3KooWFY4bzHDuQffETCMdb88DGyMmrSSgta3gyATibhvm4PPY QmQZYmNQopPejr4ennSq7Y3rAkpkdbxqs6xxSEHSzdWSLn QmPUZQgzru37wE7Nb6CeprsY23TSTBdFeBYysZ6mm3m48P 12D3KooWM3RqXZdQ4dXRuKiPxC9KaGq348pC28kdY1frjYkx26JT 12D3KooWDPfajqPZgYgJRdBAHLxBnvwPJUesvfe1fvpZfFVmJAzS]
Latency (s)    0.000000
```

- Atfer: 
```shell
PeerID         12D3KooWS6PnhhYfGdqKMgri7oqjGg868HbCYLBc1j8k2vmYyZmW
Addresses      [/ip6/2001:bc8:1830:322::1/tcp/41503 /ip6/::1/tcp/41503 /ip4/10.19.70.69/tcp/41504 /ip4/127.0.0.1/tcp/41504 /ip4/10.19.70.69/tcp/41505/ws /ip4/127.0.0.1/tcp/41505/ws /ip4/51.158.181.154/tcp/41504]
Peers          [12D3KooWML7NMZudk8H4v1AptitsTZdDqLKgEzoAdLUwuKPqkLyy 12D3KooWEcDCUbtwGhksT3gKm27NzUmo7bAB9tYxgGZKHnDs8Z9S]
Latency (s)    0.000000
```
