### ISSUE TITLE
Implement logging strategy

### ISSUE THREAD

**Issue by tchardin** [myelnet/pop#99]
Currently there is very little logs and most implemented with fmt.Print* we need a performant logging solution that can also save logs to disk when running on remote machines. Also support different levels of logging. https://github.com/ipfs/go-log might be convenient otherwise https://github.com/go-kit/kit/tree/master/log is nice as well. We can discuss.

**Comment by gallexis** [comment]
I have used [Logrus](https://github.com/sirupsen/logrus) during my previous jobs and find it pretty convenient.
You can : 
- define different levels of warning
- set formatting levels based on prod or dev : ```  if Environment == "production" {
    log.SetFormatter(&log.JSONFormatter{})
  } else {
    log.SetFormatter(&log.TextFormatter{})
  } ```
- benefit from included string formatting : ```log.Errorf("struct : %+v", mystruct)```
- - add fields to logs ``` {"animal":"penguin","level":"fatal","method":"github.com/sirupsen/arcticcreatures.migrate","msg":"a penguin swims by",
"time":"2014-03-10 19:57:38.562543129 -0400 EDT"}``` 
- define formatters whether you want you logs being displayed in JSON, YAML or just raw string
- Logs method name
- 18k stars 😁
- and many more

Also, whatever lib we use we should never have silents errors, we have some in the codebase we need to at least log.

**Comment by gallexis** [comment]
Well, Logrus is kind of slow, compared to the other https://github.com/uber-go/zap (and according to the ZAP bench).
I'll try to pplay with ZAP and Zerolog https://github.com/rs/zerolog

**Comment by tchardin** [comment]
@gallexis we can close this no?

**Comment by gallexis** [comment]
Ah yes true, I forgot to add the "closes" comment on my branch
